### ISSUE TITLE
NLTK download command

### ISSUE THREAD

**Issue by Barachia** [lcebear/memoryDialogueBot#4]
Hi!

I just finished setting up the agent and found a small something missing in the installation. I had to do `nltk.download('averaged_perceptron_tagger` before the REST-API would work, now it's all fine.

**Comment by lcebear** [comment]
Indeed, you need to run `nltk.download` on 'stopwords', 'punkt', 'vader_lexicon' and 'averaged_perceptron_tagger' as mentioned in the README file

> Hi!
> 
> I just finished setting up the agent and found a small something missing in the installation. I had to do `nltk.download('averaged_perceptron_tagger` before the REST-API would work, now it's all fine.

**Comment by Barachia** [comment]
Ah, yes, I overlooked that, thank you for pointing it out.
