### ISSUE TITLE
List of generated questions

### ISSUE THREAD

**Issue by Barachia** [lcebear/memoryDialogueBot#5]
For the questions generated, I see in the terminal/command window that multiple questions are generated for `get_question`, how can I retrieve the whole list instead of the one question?

**Comment by lcebear** [comment]
The feature of question generation is not fully developed, it is merely a test of the concept. It may ask the same questions multiple times or not stay on topic.

Although to get the entire list (in case you have some ranking), replacing `answer` with `generated_answers` in the last line of `agent_2.py` should do what you are asking for.
https://github.com/lcebear/memoryDialogueBot/blob/b644184cdb6e5bc167e207df79b1ed8653f716e4/agent_2.py#L483

**Comment by Barachia** [comment]
Alright, thanks!
